/* Localized strings contents for Turkish [Turkey] */ 

TIZEN_L10N_TR=
{
	"location" : "&nbsp;Yer Seçimi",
	"about" : "&nbsp;Hakkında",
	"title" : "Namaz Vakti",
	"wait" : "bekleyiniz...",
	"ilce" : "İlçe",
	"il" : "İl",
	"ulke" : "Ülke",
	"select_loc_alert" : "Yer seçimini yapınız!",
	"loading" : "Yükleniyor...",
	"ramazan" : "Ramazan Bayramı",
	"kurban" : "Kurban Bayramı",
	"settings" : "Ayarlar",
	"bayramlar" : "&nbsp;Bayramlar",
	"version" : "Sürüm",
	"details" : "Detaylar",
	"detailsExplanation" : "*.Yer Seçiminde Ülke alanına basarak seçim yapabilirsiniz. <br>1.Veriler Diyanet'in sitesinden alınmaktadır. <br>2.Bir aylık veriler bir kerede alınır. <br>3.Veriler alındıktan sonra bir ay boyunca internete bağlanmadan saklananır ve bu veriler kullanılır. <br>4.Icons made by Freepik from https://www.flaticon.com/ <br>5.Diyanet Namaz Vakitleri api sini sağlayan Furkan Tektaş'a çok teşekkürler",
	"vakitler_alinamadi" : "Vakitler alinamadi. Tekrar Deneyin!",
	"Miladi" : "Miladi",
	"Imsak" : "İmsak",
	"Gunes" : "Güneş",
	"Ogle" : "Öğle",
	"Ikindi" : "İkindi",
	"Aksam" : "Akşam",
	"Yatsi" : "Yatsı",
	"Hicri" : "Hicri",
	"select_country" : "Seçimi Ülke seçip yapınız",
	"notifications" : "Hatırlatıcı",
	"all" : "Tümü",
	"mins" : "dak.",
	"kible" : "Kıble",
	"kible_time" : "Kıble Saati",
	"kible_time_expl" : "Güneş yönünün kıbleyi gösterme saati:",
	"vibration" : "Titreşim",
	"off" : "Kapalı",
	"normal" : "Normal",
	"long" : "Uzun",
	"toPray" : "Kalan",
	"hours_and" : "saat",
	"minutes" : "dakika",
	"language" : "Dil",
	"Turkce" : "Türkçe",
	"English" : "English"
};
