/* Localized strings contents for default localized contents */ 

TIZEN_L10N=
{
	"location" : "Location",
	"about" : "About",
	"title" : "Prayer Time",
	"wait" : "wait...",
	"ilce" : "District",
	"il" : "City",
	"ulke" : "Country",
	"select_loc_alert" : "Select location!",
	"loading" : "Loading...",
	"ramazan" : "Ramadan Feast",
	"kurban" : "Sacrifice Feast",
	"settings" : "Settings",
	"bayramlar" : "Feasts",
	"version" : "Version",
	"details" : "Details",
	"detailsExplanation" : "*.Location selection begins with Country selection. 1.Data is retreived from Turkish Diyanet Foundation. 2.Data is retrieved for a month. 3.After that there is no need for internet connection for a month. 4.Icons made by Freepik from https://www.flaticon.com/",
	"vakitler_alinamadi" : "Could not get data. Try again!",
	"Miladi" : "Gregorian",
	"Imsak" : "Fajr",
	"Gunes" : "Tulu",
	"Ogle" : "Zuhr",
	"Ikindi" : "Asr",
	"Aksam" : "Maghrib",
	"Yatsi" : "Isha",
	"Hicri" : "Hijri",
	"select_country" : "Selection must be done from Country",
	"notifications" : "Reminders",
	"all" : "All",
	"mins" : "min.",
	"kible" : "Qibla",
	"kible_time" : "Qibla Time",
	"kible_time_expl" : "The sun direction points to Qibla at time:",
	"vibration" : "Vibration",
	"off" : "Off",
	"normal" : "Normal",
	"long" : "Long",
	"toPray" : "Remaining",
	"hours_and" : "hour(s) and",
	"minutes" : "minute(s)"
};
